# Generated by Django 5.2.7 on 2025-11-02 14:48

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('enrollment_number', models.CharField(editable=False, max_length=50, unique=True, verbose_name='شماره ثبت\u200cنام')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('approved', 'تایید شده'), ('rejected', 'رد شده'), ('active', 'فعال'), ('completed', 'تکمیل شده'), ('cancelled', 'لغو شده'), ('suspended', 'معلق'), ('withdrawn', 'انصراف')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('enrollment_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت\u200cنام')),
                ('approved_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تایید')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('total_amount', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مبلغ کل')),
                ('discount_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مبلغ تخفیف')),
                ('final_amount', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مبلغ نهایی')),
                ('paid_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مبلغ پرداخت شده')),
                ('attendance_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='نرخ حضور')),
                ('total_sessions_attended', models.PositiveIntegerField(default=0, verbose_name='جلسات حضور')),
                ('certificate_issued', models.BooleanField(default=False, verbose_name='گواهینامه صادر شده')),
                ('certificate_issue_date', models.DateField(blank=True, null=True, verbose_name='تاریخ صدور گواهینامه')),
                ('certificate_number', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='شماره گواهینامه')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cها')),
                ('cancellation_reason', models.TextField(blank=True, null=True, verbose_name='دلیل لغو')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_enrollments', to=settings.AUTH_USER_MODEL, verbose_name='تایید کننده')),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='courses.class', verbose_name='کلاس')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to=settings.AUTH_USER_MODEL, verbose_name='دانش\u200cآموز')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='courses.term', verbose_name='ترم')),
            ],
            options={
                'verbose_name': 'ثبت\u200cنام',
                'verbose_name_plural': 'ثبت\u200cنام\u200cها',
                'db_table': 'enrollments',
                'ordering': ['-enrollment_date'],
            },
        ),
        migrations.CreateModel(
            name='EnrollmentDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('document_type', models.CharField(choices=[('id_card', 'کارت ملی'), ('birth_certificate', 'شناسنامه'), ('photo', 'عکس'), ('education_certificate', 'مدرک تحصیلی'), ('medical_certificate', 'مدرک پزشکی'), ('other', 'سایر')], max_length=30, verbose_name='نوع مدرک')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('file', models.FileField(upload_to='enrollments/documents/', verbose_name='فایل')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تایید شده')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تایید')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cها')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='enrollments.enrollment', verbose_name='ثبت\u200cنام')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL, verbose_name='تایید کننده')),
            ],
            options={
                'verbose_name': 'مدرک ثبت\u200cنام',
                'verbose_name_plural': 'مدارک ثبت\u200cنام',
                'db_table': 'enrollment_documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EnrollmentTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('reason', models.TextField(verbose_name='دلیل انتقال')),
                ('request_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ درخواست')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('approved', 'تایید شده'), ('rejected', 'رد شده'), ('completed', 'انجام شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('approved_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تایید')),
                ('price_difference', models.DecimalField(decimal_places=0, default=0, help_text='مثبت: باید پرداخت شود، منفی: بازگشت داده می\u200cشود', max_digits=12, verbose_name='اختلاف قیمت')),
                ('admin_notes', models.TextField(blank=True, null=True, verbose_name='یادداشت مدیر')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_transfers', to=settings.AUTH_USER_MODEL, verbose_name='تایید کننده')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='enrollments.enrollment', verbose_name='ثبت\u200cنام')),
                ('from_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_from', to='courses.class', verbose_name='از کلاس')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_transfers', to=settings.AUTH_USER_MODEL, verbose_name='درخواست کننده')),
                ('to_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_to', to='courses.class', verbose_name='به کلاس')),
            ],
            options={
                'verbose_name': 'انتقال ثبت\u200cنام',
                'verbose_name_plural': 'انتقالات ثبت\u200cنام',
                'db_table': 'enrollment_transfers',
                'ordering': ['-request_date'],
            },
        ),
        migrations.CreateModel(
            name='PlacementTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('test_date', models.DateTimeField(verbose_name='تاریخ آزمون')),
                ('duration_minutes', models.PositiveIntegerField(default=60, verbose_name='مدت زمان (دقیقه)')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='نمره')),
                ('determined_level', models.CharField(blank=True, choices=[('beginner', 'مبتدی'), ('elementary', 'ابتدایی'), ('pre_intermediate', 'پیش متوسط'), ('intermediate', 'متوسط'), ('upper_intermediate', 'فوق متوسط'), ('advanced', 'پیشرفته'), ('proficiency', 'تخصصی')], max_length=20, null=True, verbose_name='سطح تعیین شده')),
                ('status', models.CharField(choices=[('scheduled', 'برنامه\u200cریزی شده'), ('in_progress', 'در حال برگزاری'), ('completed', 'تکمیل شده'), ('cancelled', 'لغو شده')], default='scheduled', max_length=20, verbose_name='وضعیت')),
                ('evaluated_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ارزیابی')),
                ('is_online', models.BooleanField(default=False, verbose_name='آزمون آنلاین')),
                ('is_oral', models.BooleanField(default=False, verbose_name='آزمون شفاهی')),
                ('test_file', models.FileField(blank=True, null=True, upload_to='placement_tests/questions/', verbose_name='فایل سوالات')),
                ('answer_file', models.FileField(blank=True, null=True, upload_to='placement_tests/answers/', verbose_name='فایل پاسخ')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='بازخورد')),
                ('recommendations', models.TextField(blank=True, null=True, verbose_name='توصیه\u200cها')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cها')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_tests', to='courses.course', verbose_name='دوره')),
                ('evaluated_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluated_tests', to=settings.AUTH_USER_MODEL, verbose_name='ارزیاب')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='placement_tests', to=settings.AUTH_USER_MODEL, verbose_name='دانش\u200cآموز')),
            ],
            options={
                'verbose_name': 'آزمون تعیین سطح',
                'verbose_name_plural': 'آزمون\u200cهای تعیین سطح',
                'db_table': 'placement_tests',
                'ordering': ['-test_date'],
            },
        ),
        migrations.CreateModel(
            name='WaitingList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('position', models.PositiveIntegerField(default=1, verbose_name='موقعیت در صف')),
                ('status', models.CharField(choices=[('waiting', 'در انتظار'), ('notified', 'اطلاع داده شده'), ('enrolled', 'ثبت\u200cنام شده'), ('expired', 'منقضی شده'), ('cancelled', 'لغو شده')], default='waiting', max_length=20, verbose_name='وضعیت')),
                ('notified_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ اطلاع\u200cرسانی')),
                ('notification_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='انقضای اطلاع\u200cرسانی')),
                ('is_priority', models.BooleanField(default=False, verbose_name='اولویت دارد')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cها')),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiting_lists', to='courses.class', verbose_name='کلاس')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='waiting_lists', to=settings.AUTH_USER_MODEL, verbose_name='دانش\u200cآموز')),
            ],
            options={
                'verbose_name': 'لیست انتظار',
                'verbose_name_plural': 'لیست\u200cهای انتظار',
                'db_table': 'waiting_lists',
                'ordering': ['is_priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnnualRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('academic_year', models.CharField(max_length=20, verbose_name='سال تحصیلی')),
                ('registration_date', models.DateField(verbose_name='تاریخ ثبت\u200cنام')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(verbose_name='تاریخ پایان')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('active', 'فعال'), ('expired', 'منقضی شده'), ('renewed', 'تمدید شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('registration_fee', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='شهریه ثبت\u200cنام')),
                ('is_paid', models.BooleanField(default=False, verbose_name='پرداخت شده')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پرداخت')),
                ('documents_submitted', models.BooleanField(default=False, verbose_name='مدارک ارسال شده')),
                ('documents_verified', models.BooleanField(default=False, verbose_name='مدارک تایید شده')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cها')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='annual_registrations', to='branches.branch', verbose_name='شعبه')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='annual_registrations', to=settings.AUTH_USER_MODEL, verbose_name='دانش\u200cآموز')),
            ],
            options={
                'verbose_name': 'ثبت\u200cنام سالانه',
                'verbose_name_plural': 'ثبت\u200cنام\u200cهای سالانه',
                'db_table': 'annual_registrations',
                'ordering': ['-registration_date'],
                'indexes': [models.Index(fields=['student', 'status'], name='annual_regi_student_ed8f95_idx'), models.Index(fields=['academic_year'], name='annual_regi_academi_fd6986_idx')],
                'unique_together': {('student', 'academic_year')},
            },
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['enrollment_number'], name='enrollments_enrollm_cadacb_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['student', 'status'], name='enrollments_student_929bef_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['class_obj', 'status'], name='enrollments_class_o_245db4_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['term'], name='enrollments_term_id_0e324a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'class_obj')},
        ),
        migrations.AddIndex(
            model_name='enrollmenttransfer',
            index=models.Index(fields=['enrollment', 'status'], name='enrollment__enrollm_415da6_idx'),
        ),
        migrations.AddIndex(
            model_name='placementtest',
            index=models.Index(fields=['student', 'status'], name='placement_t_student_aa9162_idx'),
        ),
        migrations.AddIndex(
            model_name='placementtest',
            index=models.Index(fields=['test_date'], name='placement_t_test_da_860b1a_idx'),
        ),
        migrations.AddIndex(
            model_name='waitinglist',
            index=models.Index(fields=['class_obj', 'status'], name='waiting_lis_class_o_c84962_idx'),
        ),
        migrations.AddIndex(
            model_name='waitinglist',
            index=models.Index(fields=['student', 'status'], name='waiting_lis_student_004c10_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='waitinglist',
            unique_together={('student', 'class_obj')},
        ),
    ]
