# Generated by Django 5.2.7 on 2025-11-04 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('enrollments', '0001_initial'),
        ('financial', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annualregistration',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='annualregistration',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='annualregistration',
            name='registration_fee',
        ),
        migrations.AddField(
            model_name='annualregistration',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ فعال\u200cسازی'),
        ),
        migrations.AddField(
            model_name='annualregistration',
            name='activated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activated_registrations', to=settings.AUTH_USER_MODEL, verbose_name='فعال کننده'),
        ),
        migrations.AddField(
            model_name='annualregistration',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True, verbose_name='دلیل لغو'),
        ),
        migrations.AddField(
            model_name='annualregistration',
            name='documents_submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ارسال مدارک'),
        ),
        migrations.AddField(
            model_name='annualregistration',
            name='invoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annual_registration', to='financial.invoice', verbose_name='فاکتور'),
        ),
        migrations.AddField(
            model_name='annualregistration',
            name='is_paid_cached',
            field=models.BooleanField(db_index=True, default=False, editable=False, help_text='این فیلد خودکار از Invoice بروز می\u200cشود', verbose_name='پرداخت شده'),
        ),
        migrations.AddField(
            model_name='annualregistration',
            name='registration_fee_amount',
            field=models.DecimalField(decimal_places=0, default=1, help_text='مبلغی که هنگام ثبت\u200cنام تعیین شده - یک snapshot از تنظیمات', max_digits=12, verbose_name='مبلغ شهریه (ثبت شده)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='annualregistration',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تایید مدارک'),
        ),
        migrations.AddField(
            model_name='annualregistration',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_annual_registrations', to=settings.AUTH_USER_MODEL, verbose_name='تایید کننده مدارک'),
        ),
        migrations.AlterField(
            model_name='annualregistration',
            name='academic_year',
            field=models.CharField(help_text='مثال: 1403-1404', max_length=20, verbose_name='سال تحصیلی'),
        ),
        migrations.AlterField(
            model_name='annualregistration',
            name='end_date',
            field=models.DateField(help_text='معمولاً 31 شهریور', verbose_name='تاریخ پایان سال تحصیلی'),
        ),
        migrations.AlterField(
            model_name='annualregistration',
            name='registration_date',
            field=models.DateField(auto_now_add=True, help_text='تاریخ رسمی ثبت\u200cنام دانش\u200cآموز', verbose_name='تاریخ ثبت\u200cنام'),
        ),
        migrations.AlterField(
            model_name='annualregistration',
            name='start_date',
            field=models.DateField(help_text='معمولاً 1 مهر', verbose_name='تاریخ شروع سال تحصیلی'),
        ),
        migrations.AlterField(
            model_name='annualregistration',
            name='status',
            field=models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('pending_payment', 'در انتظار پرداخت'), ('pending_verification', 'در انتظار تایید مدارک'), ('active', 'فعال'), ('expired', 'منقضی شده'), ('cancelled', 'لغو شده')], db_index=True, default='draft', max_length=25, verbose_name='وضعیت'),
        ),
        migrations.AddIndex(
            model_name='annualregistration',
            index=models.Index(fields=['registration_date'], name='annual_regi_registr_9652c5_idx'),
        ),
        migrations.AddIndex(
            model_name='annualregistration',
            index=models.Index(fields=['is_paid_cached', 'status'], name='annual_regi_is_paid_a25134_idx'),
        ),
    ]
