# Generated by Django 5.2.7 on 2025-11-04 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_privateclasspricing'),
        ('enrollments', '0002_remove_annualregistration_is_paid_and_more'),
        ('financial', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='enrollment',
            name='enrollments_enrollm_cadacb_idx',
        ),
        migrations.RemoveIndex(
            model_name='enrollment',
            name='enrollments_student_929bef_idx',
        ),
        migrations.RemoveIndex(
            model_name='enrollment',
            name='enrollments_class_o_245db4_idx',
        ),
        migrations.RemoveIndex(
            model_name='enrollment',
            name='enrollments_term_id_0e324a_idx',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='invoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_enrollment', to='financial.invoice', verbose_name='فاکتور'),
        ),
        migrations.AlterField(
            model_name='annualregistration',
            name='invoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annual_registration_source', to='financial.invoice', verbose_name='فاکتور'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['cancelled', 'rejected']), _negated=True), fields=('student', 'class_obj'), name='unique_active_enrollment'),
        ),
    ]
