# Generated by Django 5.2.7 on 2025-11-14 14:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_privateclasspricing'),
        ('enrollments', '0003_remove_enrollment_enrollments_enrollm_cadacb_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualRegistrationCourse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('price_at_registration', models.DecimalField(decimal_places=0, help_text='این قیمت برای صدور فاکتور استفاده می\u200cشود', max_digits=12, verbose_name='قیمت دوره در زمان ثبت\u200cنام')),
                ('status', models.CharField(choices=[('planned', 'برنامه\u200cریزی شده'), ('enrolled_in_class', 'در کلاس ثبت\u200cنام شده'), ('completed', 'تکمیل شده'), ('dropped', 'حذف شده')], default='planned', max_length=20, verbose_name='وضعیت دوره')),
                ('annual_registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enrollments.annualregistration', verbose_name='ثبت\u200cنام سالانه')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.course', verbose_name='دوره')),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annual_course', to='enrollments.enrollment', verbose_name='ثبت\u200cنام کلاس')),
            ],
            options={
                'verbose_name': 'درس ثبت\u200cنام سالانه',
                'verbose_name_plural': 'دروس ثبت\u200cنام سالانه',
                'db_table': 'annual_registration_courses',
                'unique_together': {('annual_registration', 'course')},
            },
        ),
        migrations.AddField(
            model_name='annualregistration',
            name='selected_courses',
            field=models.ManyToManyField(related_name='annual_registrations', through='enrollments.AnnualRegistrationCourse', to='courses.course', verbose_name='دروس انتخابی سالانه'),
        ),
    ]
