# Generated by Django 5.2.7 on 2025-11-16 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0004_annualregistrationcourse_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annualregistration',
            name='selected_courses',
        ),
        migrations.DeleteModel(
            name='AnnualRegistrationCourse',
        ),
    ]
