# Generated by Django 5.2.7 on 2025-11-16 16:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_subject_course_subjects'),
        ('enrollments', '0006_annualregistrationcourse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualRegistrationSubject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('price_at_registration', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='قیمت درس در زمان ثبت\u200cنام')),
                ('status', models.CharField(choices=[('planned', 'برنامه\u200cریزی شده'), ('enrolled_in_class', 'ثبت\u200cنام شده در کلاس'), ('completed', 'تکمیل شده'), ('dropped', 'حذف شده')], default='planned', max_length=20, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'درس ثبت\u200cنام سالانه',
                'verbose_name_plural': 'دروس ثبت\u200cنام سالانه',
                'db_table': 'annual_registration_subjects',
            },
        ),
        migrations.RemoveIndex(
            model_name='annualregistration',
            name='annual_regi_student_ed8f95_idx',
        ),
        migrations.RemoveIndex(
            model_name='annualregistration',
            name='annual_regi_academi_fd6986_idx',
        ),
        migrations.RemoveIndex(
            model_name='annualregistration',
            name='annual_regi_registr_9652c5_idx',
        ),
        migrations.RemoveIndex(
            model_name='annualregistration',
            name='annual_regi_is_paid_a25134_idx',
        ),
        migrations.RemoveField(
            model_name='annualregistration',
            name='activated_at',
        ),
        migrations.RemoveField(
            model_name='annualregistration',
            name='activated_by',
        ),
        migrations.RemoveField(
            model_name='annualregistration',
            name='documents_submitted_at',
        ),
        migrations.RemoveField(
            model_name='annualregistration',
            name='selected_courses',
        ),
        migrations.RemoveField(
            model_name='annualregistration',
            name='verified_at',
        ),
        migrations.RemoveField(
            model_name='annualregistration',
            name='verified_by',
        ),
        migrations.AlterField(
            model_name='annualregistration',
            name='end_date',
            field=models.DateField(verbose_name='تاریخ پایان سال تحصیلی'),
        ),
        migrations.AlterField(
            model_name='annualregistration',
            name='registration_fee_amount',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ شهریه ثابت (ثبت شده)'),
        ),
        migrations.AlterField(
            model_name='annualregistration',
            name='start_date',
            field=models.DateField(verbose_name='تاریخ شروع سال تحصیلی'),
        ),
        migrations.AddField(
            model_name='annualregistrationsubject',
            name='annual_registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enrollments.annualregistration', verbose_name='ثبت\u200cنام سالانه'),
        ),
        migrations.AddField(
            model_name='annualregistrationsubject',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annual_subject', to='enrollments.enrollment', verbose_name='ثبت\u200cنام کلاس'),
        ),
        migrations.AddField(
            model_name='annualregistrationsubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.subject', verbose_name='درس'),
        ),
        migrations.AddField(
            model_name='annualregistration',
            name='selected_subjects',
            field=models.ManyToManyField(related_name='annual_registrations', through='enrollments.AnnualRegistrationSubject', to='courses.subject', verbose_name='درس\u200cهای انتخابی سالانه'),
        ),
        migrations.AlterUniqueTogether(
            name='annualregistrationsubject',
            unique_together={('annual_registration', 'subject')},
        ),
    ]
