# Generated by Django 5.2.7 on 2025-11-16 14:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام پایه')),
                ('order', models.PositiveIntegerField(default=0, help_text='برای مرتب\u200cسازی پایه\u200cها (مثلاً اول ابتدایی = 1)', verbose_name='ترتیب')),
                ('stage', models.CharField(choices=[('preschool', 'پیش\u200cدبستانی'), ('elementary', 'ابتدایی'), ('middle_school', 'متوسطه اول'), ('high_school', 'متوسطه دوم'), ('university', 'دانشگاهی'), ('other', 'سایر')], db_index=True, default='other', max_length=20, verbose_name='مقطع تحصیلی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'پایه تحصیلی',
                'verbose_name_plural': 'پایه\u200cهای تحصیلی',
                'db_table': 'grade_levels',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='grade_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='accounts.gradelevel', verbose_name='پایه تحصیلی'),
        ),
    ]
