# Generated by Django 5.2.7 on 2025-11-29 13:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_gradelevel_studentprofile_grade_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='شماره موبایل باید به فرمت 09xxxxxxxxx باشد', regex='^09\\d{9}$')], verbose_name='شماره موبایل'),
        ),
    ]
