# Generated by Django 5.2.7 on 2025-12-05 08:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipartUpload',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('upload_id', models.CharField(max_length=255, verbose_name='شناسه آپلود S3')),
                ('s3_key', models.CharField(max_length=500, verbose_name='کلید S3')),
                ('original_filename', models.CharField(max_length=255, verbose_name='نام فایل اصلی')),
                ('content_type', models.CharField(max_length=100, verbose_name='نوع محتوا')),
                ('file_size', models.BigIntegerField(verbose_name='حجم فایل')),
                ('part_size', models.IntegerField(verbose_name='اندازه هر قسمت')),
                ('total_parts', models.IntegerField(verbose_name='تعداد کل قسمت\u200cها')),
                ('uploaded_parts', models.IntegerField(default=0, verbose_name='قسمت\u200cهای آپلود شده')),
                ('parts_data', models.JSONField(default=list, verbose_name='اطلاعات قسمت\u200cها')),
                ('status', models.CharField(choices=[('initiated', 'شروع شده'), ('in_progress', 'در حال آپلود'), ('completed', 'تکمیل شده'), ('failed', 'ناموفق'), ('aborted', 'لغو شده')], default='initiated', max_length=20, verbose_name='وضعیت')),
                ('target_folder', models.CharField(max_length=100, verbose_name='پوشه مقصد')),
                ('target_model', models.CharField(blank=True, max_length=100, verbose_name='مدل مقصد')),
                ('target_field', models.CharField(blank=True, max_length=100, verbose_name='فیلد مقصد')),
                ('target_object_id', models.CharField(blank=True, max_length=100, verbose_name='شناسه آبجکت')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تکمیل')),
                ('final_url', models.URLField(blank=True, max_length=1000, verbose_name='آدرس نهایی')),
                ('error_message', models.TextField(blank=True, verbose_name='پیام خطا')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploads', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'آپلود چندبخشی',
                'verbose_name_plural': 'آپلودهای چندبخشی',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('s3_key', models.CharField(max_length=500, unique=True, verbose_name='کلید S3')),
                ('original_filename', models.CharField(max_length=255, verbose_name='نام فایل اصلی')),
                ('content_type', models.CharField(max_length=100, verbose_name='نوع محتوا')),
                ('file_size', models.BigIntegerField(verbose_name='حجم فایل')),
                ('attached_to_model', models.CharField(blank=True, max_length=100, verbose_name='مدل پیوست')),
                ('attached_to_id', models.CharField(blank=True, max_length=100, verbose_name='شناسه پیوست')),
                ('attached_to_field', models.CharField(blank=True, max_length=100, verbose_name='فیلد پیوست')),
                ('is_temp', models.BooleanField(default=True, verbose_name='موقت')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'فایل آپلود شده',
                'verbose_name_plural': 'فایل\u200cهای آپلود شده',
                'ordering': ['-created_at'],
            },
        ),
    ]
