# Generated by Django 5.2.7 on 2025-11-04 15:18

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateClassRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('request_number', models.CharField(editable=False, max_length=50, unique=True, verbose_name='شماره درخواست')),
                ('class_type', models.CharField(choices=[('private', 'خصوصی (1 نفر)'), ('semi_private_2', 'نیمه خصوصی (2 نفر)'), ('semi_private_3', 'نیمه خصوصی (3 نفر)'), ('semi_private_4', 'نیمه خصوصی (4-5 نفر)')], default='private', max_length=20, verbose_name='نوع کلاس')),
                ('preferred_days', models.JSONField(default=list, help_text='["saturday", "monday"]', verbose_name='روزهای ترجیحی')),
                ('preferred_time_slot', models.CharField(choices=[('morning', 'صبح (8-12)'), ('afternoon', 'بعدازظهر (12-16)'), ('evening', 'عصر (16-20)'), ('night', 'شب (20-23)')], default='morning', max_length=20, verbose_name='زمان ترجیحی')),
                ('preferred_location', models.CharField(choices=[('branch', 'شعبه'), ('online', 'آنلاین'), ('home', 'منزل دانش\u200cآموز')], default='branch', max_length=20, verbose_name='محل ترجیحی')),
                ('sessions_per_week', models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)], verbose_name='تعداد جلسات در هفته')),
                ('total_sessions', models.PositiveIntegerField(default=24, validators=[django.core.validators.MinValueValidator(4)], verbose_name='تعداد کل جلسات')),
                ('session_duration', models.PositiveIntegerField(choices=[(60, '60 دقیقه'), (90, '90 دقیقه'), (120, '120 دقیقه')], default=90, verbose_name='مدت هر جلسه (دقیقه)')),
                ('preferred_start_date', models.DateField(blank=True, null=True, verbose_name='تاریخ شروع ترجیحی')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('approved', 'تایید شده'), ('rejected', 'رد شده'), ('scheduled', 'زمان\u200cبندی شده'), ('active', 'فعال'), ('completed', 'تکمیل شده'), ('cancelled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تایید')),
                ('student_notes', models.TextField(blank=True, null=True, verbose_name='یادداشت دانش\u200cآموز')),
                ('admin_notes', models.TextField(blank=True, null=True, verbose_name='یادداشت مدیر')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='دلیل رد')),
                ('additional_students', models.ManyToManyField(blank=True, limit_choices_to={'role': 'student'}, related_name='additional_private_classes', to=settings.AUTH_USER_MODEL, verbose_name='دانش\u200cآموزان اضافی')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_private_requests', to=settings.AUTH_USER_MODEL, verbose_name='تایید کننده')),
                ('assigned_teacher', models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_private_classes', to=settings.AUTH_USER_MODEL, verbose_name='معلم اختصاص داده شده')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_requests', to='branches.branch', verbose_name='شعبه')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_requests', to='courses.course', verbose_name='دوره')),
                ('created_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='private_request_source', to='courses.class', verbose_name='کلاس ایجاد شده')),
                ('preferred_teacher', models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_for_private', to=settings.AUTH_USER_MODEL, verbose_name='معلم ترجیحی')),
                ('primary_student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='private_class_requests', to=settings.AUTH_USER_MODEL, verbose_name='دانش\u200cآموز اصلی')),
            ],
            options={
                'verbose_name': 'درخواست کلاس خصوصی',
                'verbose_name_plural': 'درخواست\u200cهای کلاس خصوصی',
                'db_table': 'private_class_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
