# Generated by Django 5.2.7 on 2025-11-04 16:14

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_privateclassrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateClassPricing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('class_type', models.CharField(choices=[('private', 'خصوصی (1 نفر)'), ('semi_private_2', 'نیمه خصوصی (2 نفر)'), ('semi_private_3', 'نیمه خصوصی (3 نفر)'), ('semi_private_4', 'نیمه خصوصی (4-5 نفر)')], max_length=20, unique=True, verbose_name='نوع کلاس')),
                ('price_per_session', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت هر جلسه')),
                ('discount_24_sessions', models.DecimalField(decimal_places=2, default=5, max_digits=5, verbose_name='تخفیف 24 جلسه (درصد)')),
                ('discount_36_sessions', models.DecimalField(decimal_places=2, default=10, max_digits=5, verbose_name='تخفیف 36 جلسه (درصد)')),
                ('discount_48_sessions', models.DecimalField(decimal_places=2, default=15, max_digits=5, verbose_name='تخفیف 48 جلسه یا بیشتر (درصد)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'قیمت\u200cگذاری کلاس خصوصی',
                'verbose_name_plural': 'قیمت\u200cگذاری کلاس\u200cهای خصوصی',
                'db_table': 'private_class_pricing',
            },
        ),
    ]
