# Generated by Django 5.2.7 on 2025-11-16 15:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_gradelevel_studentprofile_grade_level'),
        ('courses', '0003_privateclasspricing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='عنوان درس')),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='کد درس')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('base_price', models.DecimalField(decimal_places=0, default=0, help_text='قیمت در صورتی که دانش\u200cآموز فقط همین درس را بردارد', max_digits=12, verbose_name='قیمت پایه تک\u200cدرس')),
                ('standard_sessions', models.PositiveIntegerField(default=24, verbose_name='تعداد جلسات استاندارد')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('grade_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='accounts.gradelevel', verbose_name='پایه تحصیلی')),
            ],
            options={
                'verbose_name': 'درس',
                'verbose_name_plural': 'درس\u200cها',
                'db_table': 'subjects',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='subjects',
            field=models.ManyToManyField(related_name='courses', to='courses.subject', verbose_name='درس\u200cهای شامل دوره'),
        ),
    ]
