# Generated by Django 5.2.7 on 2025-11-02 14:48

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('enrollments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('assignment_type', models.CharField(choices=[('homework', 'تکلیف'), ('project', 'پروژه'), ('quiz', 'آزمون کوتاه'), ('essay', 'مقاله')], default='homework', max_length=20, verbose_name='نوع')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='assignments/%Y/%m/', verbose_name='پیوست')),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='حداکثر نمره')),
                ('assigned_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ تعیین')),
                ('due_date', models.DateTimeField(verbose_name='مهلت ارسال')),
                ('late_submission_allowed', models.BooleanField(default=False, verbose_name='مجاز به ارسال دیرهنگام')),
                ('late_penalty_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='جریمه تاخیر (درصد)')),
                ('is_published', models.BooleanField(default=True, verbose_name='منتشر شده')),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='courses.class', verbose_name='کلاس')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assignments', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_assignments', to='courses.classsession', verbose_name='جلسه')),
            ],
            options={
                'verbose_name': 'تکلیف',
                'verbose_name_plural': 'تکالیف',
                'db_table': 'assignments',
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('submission_text', models.TextField(blank=True, null=True, verbose_name='متن پاسخ')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='submissions/%Y/%m/', verbose_name='فایل پاسخ')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال')),
                ('is_late', models.BooleanField(default=False, verbose_name='دیرهنگام')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='نمره')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='بازخورد')),
                ('graded_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ نمره\u200cدهی')),
                ('status', models.CharField(choices=[('submitted', 'ارسال شده'), ('graded', 'نمره داده شده'), ('returned', 'بازگشت داده شده'), ('late', 'تاخیر')], default='submitted', max_length=20, verbose_name='وضعیت')),
                ('resubmission_count', models.PositiveIntegerField(default=0, verbose_name='تعداد ارسال مجدد')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='lms.assignment', verbose_name='تکلیف')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to='enrollments.enrollment', verbose_name='ثبت\u200cنام')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_submissions', to=settings.AUTH_USER_MODEL, verbose_name='نمره دهنده')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to=settings.AUTH_USER_MODEL, verbose_name='دانش\u200cآموز')),
            ],
            options={
                'verbose_name': 'پاسخ تکلیف',
                'verbose_name_plural': 'پاسخ\u200cهای تکلیف',
                'db_table': 'assignment_submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('material_type', models.CharField(choices=[('pdf', 'PDF'), ('video', 'ویدیو'), ('audio', 'صوت'), ('presentation', 'ارائه'), ('document', 'سند'), ('link', 'لینک'), ('other', 'سایر')], max_length=20, verbose_name='نوع')),
                ('file', models.FileField(blank=True, null=True, upload_to='course_materials/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'ppt', 'pptx', 'mp4', 'mp3', 'zip', 'rar'])], verbose_name='فایل')),
                ('external_link', models.URLField(blank=True, null=True, verbose_name='لینک خارجی')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='حجم فایل (بایت)')),
                ('duration', models.PositiveIntegerField(blank=True, help_text='برای ویدیو و صوت', null=True, verbose_name='مدت زمان (ثانیه)')),
                ('is_public', models.BooleanField(default=False, verbose_name='عمومی')),
                ('available_from', models.DateTimeField(blank=True, null=True, verbose_name='در دسترس از')),
                ('available_until', models.DateTimeField(blank=True, null=True, verbose_name='در دسترس تا')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='تعداد دانلود')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید')),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_materials', to='courses.class', verbose_name='کلاس')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_materials', to='courses.classsession', verbose_name='جلسه')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_materials', to=settings.AUTH_USER_MODEL, verbose_name='آپلود شده توسط')),
            ],
            options={
                'verbose_name': 'محتوای آموزشی',
                'verbose_name_plural': 'محتوای آموزشی',
                'db_table': 'course_materials',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OnlineSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('meeting_id', models.CharField(max_length=255, unique=True, verbose_name='شناسه جلسه')),
                ('moderator_password', models.CharField(max_length=255, verbose_name='رمز مدیر')),
                ('attendee_password', models.CharField(max_length=255, verbose_name='رمز شرکت\u200cکننده')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='شروع شده در')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='پایان یافته در')),
                ('is_recorded', models.BooleanField(default=True, verbose_name='ضبط شده')),
                ('recording_url', models.URLField(blank=True, null=True, verbose_name='لینک ضبط')),
                ('recording_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='حجم ضبط (بایت)')),
                ('status', models.CharField(choices=[('scheduled', 'برنامه\u200cریزی شده'), ('live', 'در حال برگزاری'), ('ended', 'پایان یافته'), ('cancelled', 'لغو شده')], default='scheduled', max_length=20, verbose_name='وضعیت')),
                ('max_participants', models.PositiveIntegerField(default=100, verbose_name='حداکثر شرکت\u200cکننده')),
                ('allow_chat', models.BooleanField(default=True, verbose_name='چت مجاز')),
                ('allow_webcam', models.BooleanField(default=True, verbose_name='دوربین مجاز')),
                ('allow_microphone', models.BooleanField(default=True, verbose_name='میکروفون مجاز')),
                ('allow_screen_share', models.BooleanField(default=False, verbose_name='اشتراک صفحه مجاز')),
                ('class_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='online_session', to='courses.classsession', verbose_name='جلسه کلاس')),
            ],
            options={
                'verbose_name': 'جلسه آنلاین',
                'verbose_name_plural': 'جلسات آنلاین',
                'db_table': 'online_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OnlineSessionParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('joined_at', models.DateTimeField(verbose_name='پیوست در')),
                ('left_at', models.DateTimeField(blank=True, null=True, verbose_name='خروج در')),
                ('duration_seconds', models.PositiveIntegerField(default=0, verbose_name='مدت (ثانیه)')),
                ('is_moderator', models.BooleanField(default=False, verbose_name='مدیر')),
                ('online_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='lms.onlinesession', verbose_name='جلسه آنلاین')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_session_participations', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'شرکت\u200cکننده جلسه آنلاین',
                'verbose_name_plural': 'شرکت\u200cکنندگان جلسه آنلاین',
                'db_table': 'online_session_participants',
                'ordering': ['-joined_at'],
            },
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['class_obj', 'due_date'], name='assignments_class_o_0ec176_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmentsubmission',
            index=models.Index(fields=['assignment', 'status'], name='assignment__assignm_68808b_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmentsubmission',
            index=models.Index(fields=['student', 'submitted_at'], name='assignment__student_3d19fe_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assignmentsubmission',
            unique_together={('assignment', 'student')},
        ),
        migrations.AddIndex(
            model_name='coursematerial',
            index=models.Index(fields=['class_obj', 'session'], name='course_mate_class_o_fc142b_idx'),
        ),
        migrations.AddIndex(
            model_name='coursematerial',
            index=models.Index(fields=['material_type'], name='course_mate_materia_839bfd_idx'),
        ),
    ]
