# Generated by Django 5.2.7 on 2025-11-16 15:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'نقدی'), ('card', 'کارت خوان'), ('bank_transfer', 'واریز بانکی'), ('online', 'پرداخت آنلاین'), ('cheque', 'چک'), ('installment', 'اقساط'), ('credit', 'اعتبار داخلی')], max_length=20, verbose_name='روش پرداخت'),
        ),
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('balance', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='موجودی اعتبار')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_note', to=settings.AUTH_USER_MODEL, verbose_name='دانش\u200cآموز')),
            ],
            options={
                'verbose_name': 'اعتبار دانش\u200cآموز',
                'verbose_name_plural': 'اعتبارات دانش\u200cآموزان',
                'db_table': 'credit_notes',
            },
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('transaction_type', models.CharField(choices=[('refund', 'بازگشت وجه'), ('payment', 'استفاده برای پرداخت'), ('adjustment', 'تعدیل دستی')], max_length=20, verbose_name='نوع تراکنش')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ')),
                ('balance_after', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='موجودی بعد از تراکنش')),
                ('description', models.CharField(max_length=255, verbose_name='توضیحات')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('credit_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='financial.creditnote', verbose_name='اعتبار')),
                ('source_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financial.invoice', verbose_name='فاکتور مبدا/مقصد')),
            ],
            options={
                'verbose_name': 'تراکنش اعتبار',
                'verbose_name_plural': 'تراکنش\u200cهای اعتبار',
                'db_table': 'credit_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RefundRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ درخواستی')),
                ('reason', models.TextField(verbose_name='دلیل درخواست')),
                ('bank_name', models.CharField(max_length=100, verbose_name='نام بانک')),
                ('card_number', models.CharField(max_length=16, verbose_name='شماره کارت')),
                ('iban', models.CharField(max_length=26, unique=True, verbose_name='شماره شبا')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('processing', 'در حال پردازش'), ('completed', 'انجام شده'), ('rejected', 'رد شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پردازش')),
                ('transaction_receipt', models.FileField(blank=True, null=True, upload_to='refunds/', verbose_name='رسید تراکنش')),
                ('admin_notes', models.TextField(blank=True, null=True, verbose_name='یادداشت مدیر')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_refunds', to=settings.AUTH_USER_MODEL, verbose_name='پردازش کننده')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_requests', to=settings.AUTH_USER_MODEL, verbose_name='دانش\u200cآموز')),
            ],
            options={
                'verbose_name': 'درخواست بازگشت وجه',
                'verbose_name_plural': 'درخواست\u200cهای بازگشت وجه',
                'db_table': 'refund_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
