# Generated by Django 5.2.7 on 2025-11-02 14:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('enrollments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('total_students', models.PositiveIntegerField(default=0, verbose_name='کل دانش\u200cآموزان')),
                ('present_count', models.PositiveIntegerField(default=0, verbose_name='تعداد حاضر')),
                ('absent_count', models.PositiveIntegerField(default=0, verbose_name='تعداد غایب')),
                ('late_count', models.PositiveIntegerField(default=0, verbose_name='تعداد تاخیر')),
                ('excused_count', models.PositiveIntegerField(default=0, verbose_name='تعداد غیبت موجه')),
                ('attendance_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نرخ حضور')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('is_finalized', models.BooleanField(default=False, verbose_name='نهایی شده')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cها')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_report', to='courses.classsession', verbose_name='جلسه')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_reports', to=settings.AUTH_USER_MODEL, verbose_name='معلم')),
            ],
            options={
                'verbose_name': 'گزارش حضور و غیاب',
                'verbose_name_plural': 'گزارشات حضور و غیاب',
                'db_table': 'attendance_reports',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('status', models.CharField(choices=[('present', 'حاضر'), ('absent', 'غایب'), ('late', 'تاخیر'), ('excused', 'غیبت موجه'), ('sick', 'مریضی')], default='present', max_length=10, verbose_name='وضعیت')),
                ('check_in_time', models.DateTimeField(blank=True, null=True, verbose_name='زمان ورود')),
                ('check_out_time', models.DateTimeField(blank=True, null=True, verbose_name='زمان خروج')),
                ('late_minutes', models.PositiveIntegerField(default=0, verbose_name='دقیقه تاخیر')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cها')),
                ('excuse_reason', models.TextField(blank=True, null=True, verbose_name='دلیل غیبت')),
                ('is_auto_recorded', models.BooleanField(default=False, verbose_name='ثبت خودکار')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='enrollments.enrollment', verbose_name='ثبت\u200cنام')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_attendances', to=settings.AUTH_USER_MODEL, verbose_name='ثبت کننده')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='courses.classsession', verbose_name='جلسه')),
            ],
            options={
                'verbose_name': 'حضور و غیاب',
                'verbose_name_plural': 'حضور و غیاب',
                'db_table': 'attendances',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['enrollment', 'status'], name='attendances_enrollm_0067c7_idx'), models.Index(fields=['session'], name='attendances_session_f6b67d_idx')],
                'unique_together': {('enrollment', 'session')},
            },
        ),
    ]
