# Generated by Django 5.2.7 on 2025-11-02 15:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='نام')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('report_type', models.CharField(choices=[('financial', 'مالی'), ('enrollment', 'ثبت\u200cنام'), ('attendance', 'حضور و غیاب'), ('academic', 'آکادمیک'), ('teacher', 'معلمان'), ('student', 'دانش\u200cآموزان'), ('custom', 'سفارشی')], max_length=20, verbose_name='نوع گزارش')),
                ('query', models.TextField(help_text='SQL Query یا ORM query definition', verbose_name='کوئری')),
                ('columns', models.JSONField(default=list, help_text='تعریف ستون\u200cهای گزارش', verbose_name='ستون\u200cها')),
                ('filters', models.JSONField(default=list, help_text='فیلترهای قابل اعمال', verbose_name='فیلترها')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_public', models.BooleanField(default=False, verbose_name='عمومی')),
                ('allowed_roles', models.JSONField(default=list, help_text='لیست نقش\u200cهایی که می\u200cتوانند از این قالب استفاده کنند', verbose_name='نقش\u200cهای مجاز')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_templates', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
            ],
            options={
                'verbose_name': 'قالب گزارش',
                'verbose_name_plural': 'قالب\u200cهای گزارش',
                'db_table': 'report_templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('report_type', models.CharField(choices=[('financial', 'مالی'), ('enrollment', 'ثبت\u200cنام'), ('attendance', 'حضور و غیاب'), ('academic', 'آکادمیک'), ('teacher', 'معلمان'), ('student', 'دانش\u200cآموزان'), ('custom', 'سفارشی')], max_length=20, verbose_name='نوع گزارش')),
                ('parameters', models.JSONField(default=dict, help_text='پارامترهای گزارش (تاریخ، شعبه، و...)', verbose_name='پارامترها')),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/', verbose_name='فایل')),
                ('file_format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV'), ('json', 'JSON')], default='pdf', max_length=10, verbose_name='فرمت فایل')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='حجم فایل (بایت)')),
                ('is_generated', models.BooleanField(default=False, verbose_name='تولید شده')),
                ('generated_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تولید')),
                ('is_scheduled', models.BooleanField(default=False, verbose_name='زمان\u200cبندی شده')),
                ('schedule_frequency', models.CharField(blank=True, help_text='daily, weekly, monthly', max_length=20, null=True, verbose_name='دوره تکرار')),
                ('next_run', models.DateTimeField(blank=True, null=True, verbose_name='اجرای بعدی')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='branches.branch', verbose_name='شعبه')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_reports', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
            ],
            options={
                'verbose_name': 'گزارش',
                'verbose_name_plural': 'گزارشات',
                'db_table': 'reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['report_type', 'created_by'], name='reports_report__56a45f_idx'), models.Index(fields=['branch', 'created_at'], name='reports_branch__70665a_idx')],
            },
        ),
    ]
