# Generated by Django 5.2.7 on 2025-11-02 14:48

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('name', models.CharField(max_length=200, verbose_name='نام شعبه')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='کد شعبه')),
                ('phone', models.CharField(max_length=11, verbose_name='تلفن')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('province', models.CharField(max_length=100, verbose_name='استان')),
                ('city', models.CharField(max_length=100, verbose_name='شهر')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='کد پستی')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='عرض جغرافیایی')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='طول جغرافیایی')),
                ('total_capacity', models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(1)], verbose_name='ظرفیت کل')),
                ('working_hours_start', models.TimeField(blank=True, null=True, verbose_name='ساعت شروع کار')),
                ('working_hours_end', models.TimeField(blank=True, null=True, verbose_name='ساعت پایان کار')),
                ('working_days', models.CharField(default='شنبه تا پنجشنبه', help_text='مثال: شنبه تا پنجشنبه', max_length=200, verbose_name='روزهای کاری')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('inactive', 'غیرفعال'), ('under_construction', 'در حال ساخت')], default='active', max_length=20, verbose_name='وضعیت')),
                ('image', models.ImageField(blank=True, null=True, upload_to='branches/', verbose_name='تصویر')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('facilities', models.TextField(blank=True, help_text='امکانات موجود در شعبه', null=True, verbose_name='امکانات')),
                ('established_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تاسیس')),
                ('manager', models.ForeignKey(blank=True, limit_choices_to={'role': 'branch_manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_branches', to=settings.AUTH_USER_MODEL, verbose_name='مدیر شعبه')),
            ],
            options={
                'verbose_name': 'شعبه',
                'verbose_name_plural': 'شعب',
                'db_table': 'branches',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BranchStaff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('position', models.CharField(max_length=100, verbose_name='سمت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('assigned_date', models.DateField(auto_now_add=True, verbose_name='تاریخ تخصیص')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cها')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='branches.branch', verbose_name='شعبه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_assignments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کارمند شعبه',
                'verbose_name_plural': 'کارمندان شعبه',
                'db_table': 'branch_staff',
            },
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('name', models.CharField(max_length=100, verbose_name='نام کلاس')),
                ('room_number', models.CharField(max_length=20, verbose_name='شماره اتاق')),
                ('capacity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='ظرفیت')),
                ('has_projector', models.BooleanField(default=False, verbose_name='دارای پروژکتور')),
                ('has_whiteboard', models.BooleanField(default=True, verbose_name='دارای وایت برد')),
                ('has_smartboard', models.BooleanField(default=False, verbose_name='دارای اسمارت برد')),
                ('has_ac', models.BooleanField(default=False, verbose_name='دارای کولر')),
                ('has_computer', models.BooleanField(default=False, verbose_name='دارای کامپیوتر')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('equipment', models.TextField(blank=True, null=True, verbose_name='تجهیزات')),
                ('image', models.ImageField(blank=True, null=True, upload_to='classrooms/', verbose_name='تصویر')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='branches.branch', verbose_name='شعبه')),
            ],
            options={
                'verbose_name': 'کلاس فیزیکی',
                'verbose_name_plural': 'کلاس\u200cهای فیزیکی',
                'db_table': 'classrooms',
                'ordering': ['branch', 'room_number'],
            },
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['code'], name='branches_code_95622b_idx'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['status'], name='branches_status_581e1b_idx'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['city'], name='branches_city_402929_idx'),
        ),
        migrations.AddIndex(
            model_name='branchstaff',
            index=models.Index(fields=['branch', 'is_active'], name='branch_staf_branch__9baf38_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='branchstaff',
            unique_together={('branch', 'user')},
        ),
        migrations.AddIndex(
            model_name='classroom',
            index=models.Index(fields=['branch', 'is_active'], name='classrooms_branch__5cdc37_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together={('branch', 'room_number')},
        ),
    ]
