# Generated by Django 5.2.7 on 2025-11-02 14:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام')),
                ('template_type', models.CharField(choices=[('sms', 'SMS'), ('email', 'ایمیل'), ('push', 'Push'), ('in_app', 'داخل برنامه')], max_length=20, verbose_name='نوع قالب')),
                ('subject', models.CharField(blank=True, help_text='برای ایمیل', max_length=255, null=True, verbose_name='موضوع')),
                ('content', models.TextField(help_text='از {{variable}} برای متغیرها استفاده کنید', verbose_name='محتوا')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('available_variables', models.JSONField(default=list, help_text='لیست متغیرهای قابل استفاده', verbose_name='متغیرهای موجود')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'قالب اعلان',
                'verbose_name_plural': 'قالب\u200cهای اعلان',
                'db_table': 'notification_templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserNotificationSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('enable_sms', models.BooleanField(default=True, verbose_name='فعال\u200cسازی SMS')),
                ('enable_email', models.BooleanField(default=True, verbose_name='فعال\u200cسازی ایمیل')),
                ('enable_push', models.BooleanField(default=True, verbose_name='فعال\u200cسازی Push')),
                ('enable_in_app', models.BooleanField(default=True, verbose_name='فعال\u200cسازی داخل برنامه')),
                ('notify_enrollment', models.BooleanField(default=True, verbose_name='اعلان ثبت\u200cنام')),
                ('notify_payment', models.BooleanField(default=True, verbose_name='اعلان پرداخت')),
                ('notify_attendance', models.BooleanField(default=True, verbose_name='اعلان حضور و غیاب')),
                ('notify_class', models.BooleanField(default=True, verbose_name='اعلان کلاس')),
                ('notify_exam', models.BooleanField(default=True, verbose_name='اعلان آزمون')),
                ('notify_announcement', models.BooleanField(default=True, verbose_name='اعلان اطلاعیه')),
                ('quiet_hours_start', models.TimeField(blank=True, help_text='اعلان\u200cها در این بازه ارسال نمی\u200cشوند', null=True, verbose_name='شروع ساعات سکوت')),
                ('quiet_hours_end', models.TimeField(blank=True, null=True, verbose_name='پایان ساعات سکوت')),
                ('digest_mode', models.BooleanField(default=False, help_text='ارسال اعلان\u200cها به صورت خلاصه روزانه', verbose_name='حالت خلاصه')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تنظیمات اعلان کاربر',
                'verbose_name_plural': 'تنظیمات اعلانات کاربران',
                'db_table': 'user_notification_settings',
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('announcement_type', models.CharField(choices=[('general', 'عمومی'), ('urgent', 'فوری'), ('maintenance', 'تعمیرات'), ('event', 'رویداد')], default='general', max_length=20, verbose_name='نوع')),
                ('target_audience', models.CharField(choices=[('all', 'همه'), ('students', 'دانش\u200cآموزان'), ('teachers', 'معلمان'), ('staff', 'کارمندان'), ('custom', 'سفارشی')], default='all', max_length=20, verbose_name='مخاطبان')),
                ('is_published', models.BooleanField(default=False, verbose_name='منتشر شده')),
                ('publish_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انتشار')),
                ('expire_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انقضا')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='سنجاق شده')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='announcements/', verbose_name='پیوست')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_announcements', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('specific_branches', models.ManyToManyField(blank=True, related_name='announcements', to='branches.branch', verbose_name='شعب خاص')),
                ('specific_users', models.ManyToManyField(blank=True, related_name='announcements', to=settings.AUTH_USER_MODEL, verbose_name='کاربران خاص')),
            ],
            options={
                'verbose_name': 'اطلاعیه',
                'verbose_name_plural': 'اطلاعیه\u200cها',
                'db_table': 'announcements',
                'ordering': ['-is_pinned', '-publish_date'],
                'indexes': [models.Index(fields=['is_published', 'publish_date'], name='announcemen_is_publ_4e8a4d_idx'), models.Index(fields=['target_audience'], name='announcemen_target__e32955_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('message', models.TextField(verbose_name='پیام')),
                ('notification_type', models.CharField(choices=[('info', 'اطلاعات'), ('success', 'موفقیت'), ('warning', 'هشدار'), ('error', 'خطا'), ('reminder', 'یادآوری')], default='info', max_length=20, verbose_name='نوع')),
                ('category', models.CharField(choices=[('enrollment', 'ثبت\u200cنام'), ('payment', 'پرداخت'), ('attendance', 'حضور و غیاب'), ('class', 'کلاس'), ('exam', 'آزمون'), ('announcement', 'اطلاعیه'), ('system', 'سیستم')], default='system', max_length=20, verbose_name='دسته\u200cبندی')),
                ('action_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='لینک عملیات')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان خواندن')),
                ('sent_via_sms', models.BooleanField(default=False, verbose_name='ارسال SMS')),
                ('sent_via_email', models.BooleanField(default=False, verbose_name='ارسال ایمیل')),
                ('sent_via_push', models.BooleanField(default=False, verbose_name='ارسال Push')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='متادیتا')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انقضا')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='گیرنده')),
            ],
            options={
                'verbose_name': 'اعلان',
                'verbose_name_plural': 'اعلانات',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_583549_idx'), models.Index(fields=['created_at'], name='notificatio_created_e4c995_idx'), models.Index(fields=['category'], name='notificatio_categor_c83784_idx')],
            },
        ),
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('mobile', models.CharField(max_length=11, verbose_name='شماره موبایل')),
                ('message', models.TextField(verbose_name='پیام')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('sent', 'ارسال شده'), ('delivered', 'تحویل داده شده'), ('failed', 'ناموفق')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('gateway_message_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='شناسه پیام درگاه')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان ارسال')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تحویل')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='پیام خطا')),
                ('cost', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='هزینه')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_logs', to=settings.AUTH_USER_MODEL, verbose_name='گیرنده')),
            ],
            options={
                'verbose_name': 'لاگ SMS',
                'verbose_name_plural': 'لاگ\u200cهای SMS',
                'db_table': 'sms_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['mobile', 'status'], name='sms_logs_mobile_82c63f_idx'), models.Index(fields=['created_at'], name='sms_logs_created_263794_idx')],
            },
        ),
    ]
